name= input("Enter your name")
age= int(input("Enter your age"))
print(f"My name is {name} and my age is {age} ")
print("My name is ",name, "and my age is", age)
print("My name is"+ name + "and my age is " + str(age) )
print("My name is %s and my age is %d " %(name,age))
print("My name is {} and my age is {}".format(name,age))
